In [1]:
import numpy as np

In [2]:
arr = np.array([
    [0.2, 0.8, 0.4],
    [0.9, 0.1, 0.7],
    [0.3, 0.6, 0.2]
])

In [3]:
arr[arr > 0.5]

array([0.8, 0.9, 0.7, 0.6])

In [4]:
data = np.array([
    [10, 20, 30, 40],
    [20, 30, 40, 50],
    [30, 40, 50, 60]
])

In [5]:
data.shape

(3, 4)

In [6]:
data.mean(axis=0)

array([20., 30., 40., 50.])

In [7]:
data.mean(axis=1)

array([25., 35., 45.])

In [8]:
data.mean(axis=0)


array([20., 30., 40., 50.])

In [9]:
data.mean(axis=1)

array([25., 35., 45.])