# NumPy Foundations

This notebook explores fundamental NumPy operations and their use in numerical data analysis.

## Introduction

NumPy provides efficient array-based operations for numerical computing in Python. This notebook demonstrates core NumPy concepts through a series of small experiments and explains the reasoning behind each operation.

The goal is not only to execute NumPy operations, but also to understand how array structure, vectorization, broadcasting, aggregation, and memory sharing affect numerical workflows.

In [1]:
import numpy as np

## Question

What is the mean of the numbers from 1 to 10?

In [2]:

numbers = np.arange(1, 11)

mean_value = numbers.mean()

print(mean_value)

5.5


## Interpretation

The mean of the numbers from 1 to 10 is 5.5.

## Array Creation and Inspection

NumPy provides several ways to create arrays depending on the structure of the data we need. In this section, we will create arrays using `np.array`, `np.zeros`, `np.arange`, and `np.linspace` and inspect their shape, data type, and total number of elements.

Understanding these properties is important because array shape and data type directly affect how NumPy operations behave.

### Creating an Array from Existing Values

We can use `np.array` when we already have a collection of values and want to convert it into a NumPy array.

In [3]:
arr_array = np.array([10, 20, 30, 40, 50])

print("Array:", arr_array)
print("Shape:", arr_array.shape)
print("Dtype:", arr_array.dtype)
print("Size:", arr_array.size)

Array: [10 20 30 40 50]
Shape: (5,)
Dtype: int64
Size: 5


The array contains five integer values, so its shape is `(5,)` and its size is `5`. The dtype is an integer type because all values supplied to `np.array` are integers.

### Creating an Array of Zeros

`np.zeros` is useful when we need to initialize an array with a specific shape before populating it with data. We will create a 3 × 4 array to observe how its shape and size are represented.

In [4]:
arr_zeros = np.zeros((3, 4))

print("Array:")
print(arr_zeros)
print("Shape:", arr_zeros.shape)
print("Dtype:", arr_zeros.dtype)
print("Size:", arr_zeros.size)

Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)
Dtype: float64
Size: 12


The array has shape `(3, 4)`, representing three rows and four columns, giving a total size of 12 elements. The values are floating-point zeros, so NumPy uses a floating-point dtype by default for this array.

### Creating a Sequence with `np.arange`

`np.arange` is useful when we want to generate a sequence of evenly spaced values based on a specified start, stop, and step. Here we generate values from 0 up to, but not including, 10 using a step of 2.

In [5]:
arr_arange = np.arange(0, 10, 2)

print("Array:", arr_arange)
print("Shape:", arr_arange.shape)
print("Dtype:", arr_arange.dtype)
print("Size:", arr_arange.size)

Array: [0 2 4 6 8]
Shape: (5,)
Dtype: int64
Size: 5


The resulting array contains five integer values: 0, 2, 4, 6, and 8. Its shape is `(5,)` and its size is 5 because it is a one-dimensional array containing five elements.

### Creating Evenly Spaced Values with `np.linspace`

`np.linspace` is useful when we want a specific number of evenly spaced values between two endpoints. Unlike `np.arange`, we specify the number of values rather than the step size.

In [6]:
arr_linspace = np.linspace(0, 1, 5)

print("Array:", arr_linspace)
print("Shape:", arr_linspace.shape)
print("Dtype:", arr_linspace.dtype)
print("Size:", arr_linspace.size)

Array: [0.   0.25 0.5  0.75 1.  ]
Shape: (5,)
Dtype: float64
Size: 5


The resulting array contains five evenly spaced floating-point values between 0 and 1, including both endpoints. Its shape is `(5,)` and its size is 5.

### Comparison

The four functions provide different ways to construct NumPy arrays. `np.array` converts existing values into an array, `np.zeros` initializes an array with zeros, `np.arange` generates a sequence using a step size, and `np.linspace` generates a specified number of evenly spaced values.

Inspecting `shape`, `dtype`, and `size` helps us understand the structure of each array before performing further operations.

## Performance Comparison: Python Lists vs NumPy Arrays

NumPy arrays are designed for efficient numerical computation. In this experiment, we will compare a Python list and a NumPy array containing 1,000,000 numbers and measure how long it takes to double every value.

The goal is to measure the performance difference ourselves rather than assuming that NumPy is faster.

In [7]:
numbers_list = list(range(1_000_000))
numbers_array = np.arange(1_000_000)

print("List length:", len(numbers_list))
print("Array size:", numbers_array.size)

List length: 1000000
Array size: 1000000


Both structures contain 1,000,000 numerical values, so the performance comparison uses datasets of the same size.

### Doubling Values in a Python List

A Python list requires us to process its elements individually using Python's iteration mechanism. We will use a list comprehension to create a new list containing twice each value.

In [8]:
%timeit doubled_list = [x * 2 for x in numbers_list]

110 ms ± 4.14 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Doubling Values in a NumPy Array

NumPy supports vectorized arithmetic, allowing the multiplication operation to be applied to the entire array without writing a Python-level loop. We will measure the same doubling operation using NumPy.

In [9]:
%timeit doubled_array = numbers_array * 2

3.61 ms ± 239 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Performance Results

The Python list comprehension took approximately **104 ms** per loop, while the NumPy vectorized multiplication took approximately **4.56 ms** per loop.

Based on these measurements, the NumPy operation was approximately **22.8× faster** than the Python list comprehension in this experiment.

The results demonstrate the performance advantage of NumPy for large-scale numerical operations. NumPy performs the array computation through optimized vectorized operations rather than relying on Python-level iteration for each element.

### Interpretation

The NumPy operation was faster in this experiment because the numerical computation is performed using NumPy's vectorized operations rather than executing the multiplication as a Python-level operation for each element.

The experiment demonstrates why NumPy is better suited to large-scale numerical operations than a standard Python list.

## 2D Indexing, Slicing, and Boolean Masking

A dataset is commonly represented as a two-dimensional NumPy array, where rows represent observations and columns represent features.

In this section, we create a small simulated dataset and practice selecting individual rows, columns, and sub-blocks. We will also use boolean masking to filter values based on a condition.

### Creating the Dataset

We create a 10 × 4 array of random values to simulate a small numerical dataset. Each row represents an observation, while each column represents a feature.

In [10]:
data = np.random.rand(10, 4)

print("Dataset:")
print(data)
print("\nShape:", data.shape)

Dataset:
[[0.08415364 0.90531234 0.69045466 0.20363991]
 [0.28567058 0.92123562 0.30350421 0.22296473]
 [0.22804096 0.13991451 0.31324618 0.74090121]
 [0.83187921 0.80143423 0.52430648 0.7819545 ]
 [0.58181164 0.82867376 0.72557686 0.51489443]
 [0.16806541 0.39875956 0.26682695 0.64065365]
 [0.92476863 0.78770316 0.38870328 0.64887346]
 [0.99046812 0.39426793 0.77430919 0.09279082]
 [0.81234778 0.68654049 0.93006855 0.9835525 ]
 [0.48956627 0.05940996 0.04089164 0.43208915]]

Shape: (10, 4)


### Selecting a Single Row

A row represents one observation in the simulated dataset. We select the first row to examine all four feature values belonging to that observation.

In [11]:
first_row = data[0]

print("First row:")
print(first_row)
print("Shape:", first_row.shape)

First row:
[0.08415364 0.90531234 0.69045466 0.20363991]
Shape: (4,)


### Selecting a Single Column

A column represents one feature across all observations. We select the first column to examine that feature across the ten rows.

In [12]:
first_column = data[:, 0]

print("First column:")
print(first_column)
print("Shape:", first_column.shape)

First column:
[0.08415364 0.28567058 0.22804096 0.83187921 0.58181164 0.16806541
 0.92476863 0.99046812 0.81234778 0.48956627]
Shape: (10,)


### Selecting a Sub-Block

We can combine row and column slicing to extract a smaller section of the dataset. Here we select rows 2 through 5 and columns 1 through 2.

Because NumPy follows Python's slicing convention, the ending indices are exclusive, so we use `2:6` for rows and `1:3` for columns.

In [13]:
sub_block = data[2:6, 1:3]

print("Sub-block:")
print(sub_block)
print("Shape:", sub_block.shape)

Sub-block:
[[0.13991451 0.31324618]
 [0.80143423 0.52430648]
 [0.82867376 0.72557686]
 [0.39875956 0.26682695]]
Shape: (4, 2)


### Boolean Masking

We now want to identify every value in the dataset that is greater than `0.5`.

Instead of manually looping through every value and checking the condition, NumPy can create a Boolean mask and use it directly to select the matching values.

In [14]:
values_above_05 = data[data > 0.5]

print("Values greater than 0.5:")
print(values_above_05)

Values greater than 0.5:
[0.90531234 0.69045466 0.92123562 0.74090121 0.83187921 0.80143423
 0.52430648 0.7819545  0.58181164 0.82867376 0.72557686 0.51489443
 0.64065365 0.92476863 0.78770316 0.64887346 0.99046812 0.77430919
 0.81234778 0.68654049 0.93006855 0.9835525 ]


### Interpretation

Boolean masking allows us to filter the dataset using a condition without writing a manual loop. The expression `data > 0.5` creates a Boolean array containing `True` where the condition is satisfied and `False` elsewhere. Using this Boolean array as an index returns only the values greater than `0.5`.

The result is one-dimensional because boolean indexing extracts the matching elements rather than preserving the original two-dimensional structure.

## Broadcasting and Mean-Centering

Broadcasting allows NumPy to perform operations between arrays with compatible shapes without manually looping through the elements.

We will use the same simulated dataset from the previous section, calculate the mean of each feature, and subtract those means from every row. This mean-centering operation is a common numerical preprocessing step.

### Calculating Column Means

We calculate the mean along `axis=0` so that each column is reduced to a single value. The resulting one-dimensional array contains the mean of each feature.

In [15]:
column_means = data.mean(axis=0)

print("Column means:")
print(column_means)
print("Shape:", column_means.shape)

Column means:
[0.53967722 0.59232516 0.4957888  0.52623144]
Shape: (4,)


### Mean-Centering with Broadcasting

We subtract the four column means from every row. Because the dataset has shape `(10, 4)` and the column means have shape `(4,)`, NumPy can broadcast the one-dimensional means across all ten rows.

No manual loop is required.

In [16]:
centered_data = data - column_means

In [17]:
print("Centered data:")
print(centered_data)

print("\nShape:", centered_data.shape)

Centered data:
[[-0.45552359  0.31298719  0.19466586 -0.32259152]
 [-0.25400664  0.32891046 -0.19228459 -0.3032667 ]
 [-0.31163626 -0.45241065 -0.18254262  0.21466977]
 [ 0.29220199  0.20910907  0.02851768  0.25572307]
 [ 0.04213442  0.2363486   0.22978806 -0.01133701]
 [-0.37161181 -0.19356559 -0.22896185  0.11442221]
 [ 0.3850914   0.195378   -0.10708552  0.12264203]
 [ 0.45079089 -0.19805722  0.27852039 -0.43344062]
 [ 0.27267055  0.09421533  0.43427975  0.45732106]
 [-0.05011095 -0.53291519 -0.45489716 -0.09414229]]

Shape: (10, 4)


### Verifying the Mean-Centered Data

After subtracting each column's mean, the mean of each column in the centered dataset should be approximately zero. We can verify this by calculating the column means again.

In [18]:
centered_means = centered_data.mean(axis=0)

print("Means after centering:")
print(centered_means)

Means after centering:
[ 4.44089210e-17 -8.88178420e-17 -1.11022302e-17 -1.11022302e-16]


### Interpretation

Subtracting each column's mean centers every feature around zero. The verification step shows that the mean of each centered column is approximately zero.

The important part is that broadcasting allowed the same four column means to be applied to all ten rows without writing a manual loop. This demonstrates how NumPy can perform efficient preprocessing operations on entire datasets.

## Axis Aggregation

NumPy aggregation functions such as `mean`, `sum`, `min`, and `max` can reduce an array along a specific axis.

In this section, we calculate the mean along `axis=0` and `axis=1` to understand how the direction of aggregation changes both the meaning and shape of the result.

### Mean Along Axis 0

We calculate the mean using `axis=0` to obtain one mean value for each column. Since our dataset contains four columns, the result should contain four values.

In [19]:
mean_axis_0 = data.mean(axis=0)

print("Mean along axis=0:")
print(mean_axis_0)

print("Shape:", mean_axis_0.shape)

Mean along axis=0:
[0.53967722 0.59232516 0.4957888  0.52623144]
Shape: (4,)


In [20]:
np.array_equal(mean_axis_0, column_means)

True

### Mean Along Axis 1

We calculate the mean using `axis=1` to obtain one mean value for each row. Since our dataset contains ten rows, the result should contain ten values.

In [21]:
mean_axis_1 = data.mean(axis=1)

print("Mean along axis=1:")
print(mean_axis_1)

print("Shape:", mean_axis_1.shape)

Mean along axis=1:
[0.47089014 0.43334379 0.35552571 0.7348936  0.66273917 0.36857639
 0.68751213 0.56295902 0.85312733 0.25548925]
Shape: (10,)


### Comparing the Two Aggregations

The original dataset has shape `(10, 4)`, representing ten observations and four features.

When using `axis=0`, NumPy collapses the row dimension and produces one mean for each of the four columns, resulting in shape `(4,)`.

When using `axis=1`, NumPy collapses the column dimension and produces one mean for each of the ten rows, resulting in shape `(10,)`.

In [22]:
print("Original shape:", data.shape)
print("axis=0 result shape:", mean_axis_0.shape)
print("axis=1 result shape:", mean_axis_1.shape)

Original shape: (10, 4)
axis=0 result shape: (4,)
axis=1 result shape: (10,)


### Interpretation

The axis determines which dimension of the array is reduced during aggregation. For the `(10, 4)` dataset, `axis=0` produces four values because it calculates one mean for each column, while `axis=1` produces ten values because it calculates one mean for each row.

Checking the shape of the result makes the direction of aggregation clear and helps prevent axis-related mistakes.

## Reshaping: View or Copy?

Reshaping changes the dimensions of a NumPy array without changing the number of elements. However, a reshaped array may share the same underlying memory as the original array.

In this experiment, we will reshape an array, modify the reshaped version, and check whether the original array is affected. Before running the modification, we will make a prediction about what will happen.

### Creating the Original Array

We create a one-dimensional array containing six values. This gives us an array that can be reshaped into different two-dimensional structures while preserving the same six elements.

In [23]:
reshape_original = np.array([1, 2, 3, 4, 5, 6])

print("Original array:")
print(reshape_original)

print("Shape:", reshape_original.shape)

Original array:
[1 2 3 4 5 6]
Shape: (6,)


### Reshaping the Array

We reshape the one-dimensional array into a 2 × 3 array. The total number of elements remains six because `2 × 3 = 6`.

In [24]:
reshaped = reshape_original.reshape(2, 3)

print("Reshaped array:")
print(reshaped)

print("Shape:", reshaped.shape)

Reshaped array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


### Prediction Before Modification

Before modifying the reshaped array, I predict that changing an element in the reshaped array will also change the corresponding value in the original array because `reshape()` can return a view that shares the same underlying memory.

### Modifying the Reshaped Array

We now modify the first element of the reshaped array and then inspect both arrays to determine whether they share the same underlying data.

In [25]:
reshaped[0, 0] = 100

print("Reshaped array:")
print(reshaped)

print("\nOriginal array:")
print(reshape_original)

Reshaped array:
[[100   2   3]
 [  4   5   6]]

Original array:
[100   2   3   4   5   6]


### Verifying Memory Sharing

We can use `np.shares_memory()` to check whether the original and reshaped arrays reference the same underlying memory.

In [26]:
shares_memory = np.shares_memory(reshape_original, reshaped)

print("Shares memory:", shares_memory)

Shares memory: True


### Observation

The modification of `reshaped[0, 0]` also changed the first element of `reshape_original`. `np.shares_memory()` returned `True`, confirming that the reshaped array shares the underlying memory of the original array.

This matched my prediction that modifying the reshaped array could affect the original array.

### Comparing with an Explicit Copy

To distinguish a view from an independent array, we create a copy of the reshaped array. Changes to the copy should not affect the original array.

In [27]:
copied = reshape_original.reshape(2, 3).copy()

copied[0, 0] = 999

print("Copied array:")
print(copied)

print("\nOriginal array:")
print(reshape_original)

print("\nShares memory:", np.shares_memory(reshape_original, copied))

Copied array:
[[999   2   3]
 [  4   5   6]]

Original array:
[100   2   3   4   5   6]

Shares memory: False


### Interpretation

The experiment showed that the reshaped array shared memory with the original array, so modifying the reshaped array also modified the original. This demonstrates the difference between a view and an independent copy.

When an independent array is required, `.copy()` can be used explicitly. This is important when working with data because modifying a view can unintentionally modify the original dataset.

## Exploring NumPy Documentation from the Notebook

Jupyter provides interactive documentation tools that allow us to investigate functions without leaving the notebook. In this section, we will choose a NumPy function that we have not used yet and inspect its documentation using `Shift+Tab` and the trailing `?` syntax.

In [28]:
np.clip?

Signature:      
np.clip(
    a,
    a_min=<no value>,
    a_max=<no value>,
    out=None,
    *,
    min=<no value>,
    max=<no value>,
    **kwargs,
)
Call signature:  np.clip(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function clip at 0x000001886F059DD0>
File:            d:\subhan folder\arhamsoft_internship\week5_17th_august_2027_monday\venv\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Clip (limit) the values in an array.

Given an interval, values outside the interval are clipped to
the interval edges.  For example, if an interval of ``[0, 1]``
is specified, values smaller than 0 become 0, and values larger
than 1 become 1.

Equivalent to but faster than ``np.minimum(a_max, np.maximum(a, a_min))``.

No check is performed to ensure ``a_min < a_max``.

Parameters
----------
a : array_like
    Array containing elements to clip.
a_min, a_max : array_like or None
    Minimum and maximum value. If ``None``, clipping is not performed on

In [29]:
values = np.array([-5, 2, 8, 15, 20])

clipped = np.clip(values, 0, 10)

print("Original:", values)
print("Clipped:", clipped)

Original: [-5  2  8 15 20]
Clipped: [ 0  2  8 10 10]


### Interpretation

`np.clip` limits values to a specified minimum and maximum range. The documentation was accessed directly from the Jupyter environment using `Shift+Tab` and the trailing `?`, demonstrating that we can investigate unfamiliar functions without leaving the notebook.

## Conclusion

This notebook demonstrated several fundamental NumPy concepts used in numerical data analysis.

We created and inspected arrays using multiple NumPy functions, measured the performance advantage of vectorized operations, practiced multidimensional indexing and boolean masking, used broadcasting for mean-centering, compared aggregation along different axes, and investigated the difference between views and copies when reshaping arrays.

These operations form the foundation for working with numerical datasets and provide the basis for more advanced data analysis and preprocessing workflows.